version: 2

jobs:
  build:
    docker:
      - image: iqlusion/rust-ci:20180729.2 # bump cache keys when modifying this
    environment:
    steps:
      - checkout
      - restore_cache:
           key: cache-20180729.2 # bump save_cache key below too
      - run:
          name: rustfmt
          command: |
            cargo +$RUST_NIGHTLY_VERSION fmt --version
            cargo +$RUST_NIGHTLY_VERSION fmt --all -- --check
      - run:
          name: clippy
          command: |
            cargo +$RUST_NIGHTLY_VERSION clippy --version
            cargo +$RUST_NIGHTLY_VERSION clippy --all
      - run:
          name: build
          command: |
            rustc --version
            cargo --version
            cargo build
      - run:
          name: test
          command: |
            rustc --version
            cargo --version
            cargo test
      - run:
          name: audit
          command: |
            cargo audit --version
            cargo audit
      - save_cache:
          key: cache-20180729.2 # bump restore_cache key above too
          paths:
            - "~/.cargo"
            - "./target"
